// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvezpnametbojuqkvigs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZXpwbmFtZXRib2p1cWt2aWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjQ0MTEsImV4cCI6MjA2ODk0MDQxMX0.wX6TbpEz0F3VyompUSNAmLg8cma4sps62xOv7qhEfGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});